language: python

python: 
  - "2.6" 
  - "2.7"
  - "3.2"
  - "3.4"
  
install:
    #  This requires numpy etc...
    #- pip install git+https://github.com/NeuralEnsemble/pyelectro.git
    
    - pip install . -r requirements.txt
    
script:
    - pynml -h
    - ./test.sh
    - ls -alt
